import { useState } from 'react';
import { ArrowUpRight, MapPin, Phone, Mail } from 'lucide-react';
import PageIntro from '@/components/school/PageIntro';
import { school } from '@/components/school/data';
export default function Contact() {
  const [form, setForm] = useState({ name: '', email: '', subject: '', message: '' });
  const change = e => setForm({ ...form, [e.target.name]: e.target.value });
  const submit = e => { e.preventDefault(); const body = `Name: ${form.name}\nEmail: ${form.email}\n\n${form.message}`; window.location.href = `mailto:${school.email}?subject=${encodeURIComponent(form.subject)}&body=${encodeURIComponent(body)}`; };
  return <><PageIntro index="07" label="CONTACT" title={<>We’d love to <em>hear from you.</em></>} description="Have a question about Queen of Peace? Reach out and start a conversation."/><section className="inner-section"><div className="shell contact-grid"><div className="contact-details"><span className="eyebrow">GET IN TOUCH</span><h2>Find us in <em>Mbaise.</em></h2><div className="contact-item"><MapPin size={20}/><div><span>VISIT</span><p>{school.address}</p></div></div><div className="contact-item"><Phone size={20}/><div><span>CALL</span><a href={`tel:${school.phone}`}>{school.phone}</a></div></div><div className="contact-item"><Mail size={20}/><div><span>EMAIL</span><a href={`mailto:${school.email}`}>{school.email}</a></div></div><a href={`https://wa.me/234${school.phone.slice(1)}`} target="_blank" rel="noopener noreferrer" className="under-link">Message on WhatsApp <ArrowUpRight size={18}/></a><p className="hours-note">For visiting hours, please call the school before your visit.</p></div><div className="form-panel"><span className="eyebrow">SEND AN ENQUIRY</span><h3>Tell us what’s on your mind.</h3><p>Completing this form opens your email app with a prepared message. Please send it there to reach the school.</p><form onSubmit={submit}><div className="form-row"><label>Your name<input required name="name" autoComplete="name" value={form.name} onChange={change} placeholder="Your full name"/></label><label>Email address<input required type="email" name="email" autoComplete="email" value={form.email} onChange={change} placeholder="you@example.com"/></label></div><label>Subject<input required name="subject" value={form.subject} onChange={change} placeholder="What is your enquiry about?"/></label><label>Message<textarea required minLength={10} name="message" value={form.message} onChange={change} placeholder="Write your message here..." rows={5}/></label><button type="submit" className="button button-blue">Open email draft <ArrowUpRight size={17}/></button></form></div></div></section><section className="map-section"><div className="shell map-grid"><div><span className="eyebrow">OUR LOCATION</span><h2>Rooted in <em>community.</em></h2><p>{school.address}</p><a className="under-link" href={`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(school.address)}`} target="_blank" rel="noopener noreferrer">Open in Google Maps <ArrowUpRight size={18}/></a></div><div className="map-panel"><MapPin size={32}/><strong>Oboama Ezi-west</strong><span>Ezinihitte Mbaise · Imo State · Nigeria</span></div></div></section></>;
}